/**
 * Captures officielles de l'application, telles que publiées sur l'App Store
 * (fiche « Abyssia — AI Chat & Tools », version 4.1.0).
 *
 * Les images sont déjà mises en scène par Apple : elles contiennent le cadre du
 * téléphone et un titre. On les affiche donc telles quelles, sans coque ajoutée.
 * Source : https://apps.apple.com/us/app/abyssia-ai-chat-tools/id6776822178
 */
export const SCREENS = [
  { key: 'chat', file: '/screens/05-chat.webp', accent: 'violet' },
  { key: 'skills', file: '/screens/03-skills.webp', accent: 'violet' },
  { key: 'cours', file: '/screens/01-cours.webp', accent: 'violet' },
  { key: 'plan', file: '/screens/02-plan.webp', accent: 'violet' },
  { key: 'accueil', file: '/screens/04-accueil.webp', accent: 'violet' },
  { key: 'dashboard', file: '/screens/08-dashboard.webp', accent: 'orange' },
  { key: 'pomodoro', file: '/screens/07-pomodoro.webp', accent: 'rose' },
  { key: 'progression', file: '/screens/09-progression.webp', accent: 'amber' },
  { key: 'coach', file: '/screens/06-coach.webp', accent: 'emerald' },
  { key: 'navigateur', file: '/screens/10-navigateur.webp', accent: 'cyan' },
];

/** Lueur colorée derrière chaque capture, accordée à sa dominante. */
export const ACCENT_GLOW = {
  violet: 'bg-violet-600',
  orange: 'bg-orange-500',
  rose: 'bg-rose-500',
  amber: 'bg-amber-500',
  emerald: 'bg-emerald-500',
  cyan: 'bg-cyan-500',
};

export const SCREEN_LABELS = {
  fr: {
    chat: { title: 'Chat IA', desc: "Plusieurs personnalités, une seule conversation." },
    skills: { title: 'Skills dans le chat', desc: "Tapez / pour lancer un cours, une fiche, un quiz." },
    cours: { title: 'Cours rédigés par l’IA', desc: 'Leçons longues, exemples traités et démonstrations.' },
    plan: { title: 'Fiches, exercices, quiz', desc: 'Choisissez la matière, le chapitre et le niveau.' },
    accueil: { title: 'Tous vos outils', desc: 'Sept catégories, plus rien à chercher.' },
    dashboard: { title: 'Brief quotidien', desc: "Votre journée résumée par l’IA, avec un score." },
    pomodoro: { title: 'Pomodoro', desc: 'Minuteur de concentration synchronisé Dynamic Island.' },
    progression: { title: 'Progression', desc: 'XP, séries actives et badges à débloquer.' },
    coach: { title: 'Coach entretien', desc: "Questions et corrections générées par l’IA." },
    navigateur: { title: 'Navigateur intégré', desc: 'Cherchez et lisez sans quitter Abyssia.' },
  },
  en: {
    chat: { title: 'AI chat', desc: 'Several personalities, one conversation.' },
    skills: { title: 'Skills inside the chat', desc: 'Type / to start a course, a summary, a quiz.' },
    cours: { title: 'Courses written by AI', desc: 'Long lessons, worked examples and proofs.' },
    plan: { title: 'Summaries, exercises, quizzes', desc: 'Pick your subject, chapter and school level.' },
    accueil: { title: 'All your tools', desc: 'Seven categories, nothing left to hunt for.' },
    dashboard: { title: 'Daily brief', desc: 'Your day summed up by AI, with a score.' },
    pomodoro: { title: 'Pomodoro', desc: 'Focus timer synced with the Dynamic Island.' },
    progression: { title: 'Progress', desc: 'XP, active streaks and badges to unlock.' },
    coach: { title: 'Interview coach', desc: 'Questions and corrections generated by AI.' },
    navigateur: { title: 'Built-in browser', desc: 'Search and read without leaving Abyssia.' },
  },
  es: {
    chat: { title: 'Chat con IA', desc: 'Varias personalidades, una sola conversación.' },
    skills: { title: 'Skills en el chat', desc: 'Escribe / para lanzar un curso, una ficha, un test.' },
    cours: { title: 'Cursos escritos por la IA', desc: 'Lecciones largas, ejemplos resueltos y demostraciones.' },
    plan: { title: 'Fichas, ejercicios, test', desc: 'Elige la asignatura, el capítulo y el nivel.' },
    accueil: { title: 'Todas tus herramientas', desc: 'Siete categorías, nada que buscar.' },
    dashboard: { title: 'Resumen diario', desc: 'Tu día resumido por la IA, con una puntuación.' },
    pomodoro: { title: 'Pomodoro', desc: 'Temporizador de enfoque sincronizado con Dynamic Island.' },
    progression: { title: 'Progreso', desc: 'XP, rachas activas y medallas por desbloquear.' },
    coach: { title: 'Coach de entrevistas', desc: 'Preguntas y correcciones generadas por la IA.' },
    navigateur: { title: 'Navegador integrado', desc: 'Busca y lee sin salir de Abyssia.' },
  },
  zh: {
    chat: { title: 'AI 聊天', desc: '多种人格，一个对话。' },
    skills: { title: '聊天内的技能', desc: '输入 / 即可生成课程、摘要或测验。' },
    cours: { title: 'AI 撰写的课程', desc: '完整讲解、例题与推导过程。' },
    plan: { title: '讲义、练习、测验', desc: '选择科目、章节与年级。' },
    accueil: { title: '全部工具', desc: '七大分类，无需再找。' },
    dashboard: { title: '每日简报', desc: 'AI 为你总结一天，并给出评分。' },
    pomodoro: { title: '番茄钟', desc: '与灵动岛同步的专注计时器。' },
    progression: { title: '进度', desc: '经验值、连续记录与待解锁徽章。' },
    coach: { title: '面试教练', desc: 'AI 生成的问题与修改建议。' },
    navigateur: { title: '内置浏览器', desc: '无需离开 Abyssia 即可搜索和阅读。' },
  },
  it: {
    chat: { title: 'Chat con IA', desc: 'Più personalità, una sola conversazione.' },
    skills: { title: 'Skills dentro la chat', desc: 'Digita / per avviare un corso, una scheda, un quiz.' },
    cours: { title: "Corsi scritti dall’IA", desc: 'Lezioni lunghe, esempi svolti e dimostrazioni.' },
    plan: { title: 'Schede, esercizi, quiz', desc: 'Scegli la materia, il capitolo e il livello.' },
    accueil: { title: 'Tutti i tuoi strumenti', desc: 'Sette categorie, nulla da cercare.' },
    dashboard: { title: 'Riepilogo giornaliero', desc: "La tua giornata riassunta dall’IA, con un punteggio." },
    pomodoro: { title: 'Pomodoro', desc: 'Timer di concentrazione sincronizzato con la Dynamic Island.' },
    progression: { title: 'Progressi', desc: 'XP, serie attive e badge da sbloccare.' },
    coach: { title: 'Coach per i colloqui', desc: "Domande e correzioni generate dall’IA." },
    navigateur: { title: 'Browser integrato', desc: 'Cerca e leggi senza uscire da Abyssia.' },
  },
  ru: {
    chat: { title: 'ИИ-чат', desc: 'Несколько личностей, один разговор.' },
    skills: { title: 'Навыки прямо в чате', desc: 'Введите /, чтобы создать курс, конспект или тест.' },
    cours: { title: 'Курсы, написанные ИИ', desc: 'Развёрнутые уроки, разобранные примеры и доказательства.' },
    plan: { title: 'Конспекты, задания, тесты', desc: 'Выберите предмет, главу и уровень.' },
    accueil: { title: 'Все ваши инструменты', desc: 'Семь категорий — искать больше нечего.' },
    dashboard: { title: 'Ежедневная сводка', desc: 'Ваш день в изложении ИИ, с оценкой.' },
    pomodoro: { title: 'Помодоро', desc: 'Таймер концентрации, связанный с Dynamic Island.' },
    progression: { title: 'Прогресс', desc: 'Опыт, активные серии и значки для разблокировки.' },
    coach: { title: 'Коуч по собеседованиям', desc: 'Вопросы и разбор ответов от ИИ.' },
    navigateur: { title: 'Встроенный браузер', desc: 'Ищите и читайте, не выходя из Abyssia.' },
  },
  uk: {
    chat: { title: 'ШІ-чат', desc: 'Кілька особистостей, одна розмова.' },
    skills: { title: 'Навички просто в чаті', desc: 'Введіть /, щоб створити курс, конспект або тест.' },
    cours: { title: 'Курси, написані ШІ', desc: 'Докладні уроки, розібрані приклади та доведення.' },
    plan: { title: 'Конспекти, вправи, тести', desc: 'Оберіть предмет, розділ і рівень.' },
    accueil: { title: 'Усі ваші інструменти', desc: 'Сім категорій — більше нічого шукати.' },
    dashboard: { title: 'Щоденне зведення', desc: 'Ваш день у викладі ШІ, з оцінкою.' },
    pomodoro: { title: 'Помодоро', desc: 'Таймер концентрації, синхронізований з Dynamic Island.' },
    progression: { title: 'Прогрес', desc: 'Досвід, активні серії та значки для розблокування.' },
    coach: { title: 'Коуч зі співбесід', desc: 'Запитання та виправлення, згенеровані ШІ.' },
    navigateur: { title: 'Вбудований браузер', desc: 'Шукайте й читайте, не виходячи з Abyssia.' },
  },
};

export const GALLERY_LABELS = {
  fr: { microBadge: "Captures officielles de l’App Store", title: "Voyez l’application avant de l’installer", subtitle: "Dix écrans réels d’Abyssia, directement repris de la fiche App Store." },
  en: { microBadge: 'Official App Store screenshots', title: 'See the app before you install it', subtitle: 'Ten real Abyssia screens, taken straight from the App Store listing.' },
  es: { microBadge: 'Capturas oficiales del App Store', title: 'Mira la app antes de instalarla', subtitle: 'Diez pantallas reales de Abyssia, tomadas de la ficha del App Store.' },
  zh: { microBadge: 'App Store 官方截图', title: '安装前先看看这款应用', subtitle: '十张真实的 Abyssia 界面，直接取自 App Store 页面。' },
  it: { microBadge: "Screenshot ufficiali dell’App Store", title: "Guarda l’app prima di installarla", subtitle: "Dieci schermate reali di Abyssia, prese dalla scheda App Store." },
  ru: { microBadge: 'Официальные скриншоты из App Store', title: 'Посмотрите приложение до установки', subtitle: 'Десять настоящих экранов Abyssia прямо со страницы App Store.' },
  uk: { microBadge: 'Офіційні знімки з App Store', title: 'Подивіться застосунок перед встановленням', subtitle: 'Десять справжніх екранів Abyssia просто зі сторінки App Store.' },
};

export const CAROUSEL_LABELS = {
  fr: { prev: 'Capture précédente', next: 'Capture suivante' },
  en: { prev: 'Previous screenshot', next: 'Next screenshot' },
  es: { prev: 'Captura anterior', next: 'Captura siguiente' },
  zh: { prev: '上一张截图', next: '下一张截图' },
  it: { prev: 'Schermata precedente', next: 'Schermata successiva' },
  ru: { prev: 'Предыдущий скриншот', next: 'Следующий скриншот' },
  uk: { prev: 'Попередній знімок', next: 'Наступний знімок' },
};
